ONSdigital/dp-frontend-search-controller

README.md, handlers/filter.go, main.go
Changes search query to api - the ones we missed in the first round
Check that the changes make sense
And that there aren't any liguering references to search query
Anyone
=> Changes clinging remains of search query to search api

go.mod, go.sum
Updates `dp-api-clients-go` to  `v1.33.4`
Check changes make sense
Anyone
=> Updates dp-api-clients-go to  v1.33.4

go.mod, go.sum
Updates version of `dp-api-clients-go` to v1.33.4. This version which contains a name change (from `dp-query` to `dp-search`). This affects the healthcheck message
Check that the correct commits have been included
Anyone
=> Release 0.4.0

go.mod, go.sum, handlers/handlers.go, handlers/handlers_test.go, mapper/mapper.go, mapper/mapper_test.go
- add dpcontrollers middleware to handle detecting language set/chosen by user
- map language to page model to send to renderer
Anyone
=> Detect user language preference

go.mod, go.sum, service/service_test.go
- Addressed changes in the release PR (https://github.com/ONSdigital/dp-frontend-search-controller/pull/24)
- This means that the changes will be available in `develop` once merged and then will be picked up by the release PR, where it will then be available in `master` once that is merged
- Check the code changes address the comments in the release PR
- Anyone
=> addressing comments on release PR

go.mod, go.sum, handlers/clients.go, handlers/clients_mock.go, handlers/handlers.go, handlers/handlers_test.go, mapper/data/mock_department_response.json, mapper/mapper.go, mapper/mapper_test.go, mapper/search_mock.go
=> Add departments

README.md, config/config.go, config/config_test.go
Remove search api url config property
Anyone
=> Remove search api url config property

go.mod, go.sum, mapper/mapper.go
Map additional suggestions from api response to model
Anyone
=> Add additional suggestions

mapper/mapper.go
=> Set page type

data/pagination.go, data/pagination_test.go, go.mod, go.sum, mapper/mapper.go, model/search.go
Move models into controller. Use internal models rather dp-frontend-models 
Anyone
=> Move models into controller

assets/locale/service.cy.toml, assets/locale/service.en.toml, assets/templates/partials/bar.tmpl, assets/templates/partials/department.tmpl, assets/templates/partials/filter.tmpl, assets/templates/partials/pagination.tmpl, assets/templates/partials/results.tmpl, assets/templates/partials/sort.tmpl, assets/templates/search.tmpl
Move assets (templates/locales) to controller
Sanity check. No need to review templates these have been a lift & shift
Anyone
=> Move assets to controller

assets/templates/partials/results.tmpl
Remove keyword highlighting from title and keywords
Anyone
=> Remove keyword highlighting from title and keywords

mapper/mapper.go
- use and return base page model as well as page specific data
Anyone
=> return full page from mapper

README.md
Added instructions for running new search in the UI. 
See that tests pass and instructions make sense. 
Anyone but me.
=> add instructions for running new search

config/config.go
updated to point dp-design-system
Describe the steps required to test the changes.
=> updated patternAssetPath to pint at dp-design-system

data/filter.go, data/filter_test.go, go.mod, go.sum
use default list of content types if no filters are selected. prevent unwanted indexed content types being returned in search
Anyone
=> use default list of content types if no filters are selected. prevent unwanted indexed content types being returned in search

go.mod, go.sum
Update reference to latest [dp-renderer](https://github.com/ONSdigital/dp-renderer/releases) release. 
See that latest release matches go.mod file 
Anyone but me.
=> update reference to library

mapper/mapper.go
Add total results to data layer. 
Run new search: 
- run `dp-frontend-search-controller`
- run `dp-search-api`
- set `SearchRoutesEnabled` to `true`
Pull this branch and see that `numberOfResults` is displayed in search console after running `console.log(window.dataLayer)`. 
Anyone but me.
=> map count to page model

assets/templates/partials/filter.tmpl, assets/templates/partials/results.tmpl, assets/templates/partials/sort.tmpl, assets/templates/partials/summary.tmpl, assets/templates/search.tmpl, config/config.go, go.mod, go.sum, mapper/mapper.go
This PR is to get the general page layout styling in place.  There are still outstanding items, but these will be tackled in subsequent PR's.  _Note that this feature is currently switched off in the production app._
fixes:
- filter checkbox and results separation and alignment
- alignment and padding of the filter title and sort dropdown
- Rearranged the DOM structure of the search template to allow for easier styling
- pointed to the config to the new dp-design-system commit
- set the `SearchDisabled` go flag to false.  this allows the use of the site-wide search in the search results page
- updated search results page styling to confirm with figma designs
- view figma design: https://www.figma.com/file/kAyqXh8f02S0UXauLubSkF/Beta-release-reference?node-id=0%3A1
- the new layout, …
=> updated dp-design-system commit ref

assets/locales/service.cy.toml, assets/locales/service.en.toml, data/filter.go
Add new content types mapping
Anyone
=> Add new content types mapping

assets/templates/partials/filter.tmpl
fix new search in develop - wrong field passed
=> fix search field

mapper/mapper.go, mapper/mapper_test.go, model/search.go
Add filters property to page model to decrease unnecessary logic in templates 
Anyone
=> Add filters property to page model

README.md
Update instructions for running new search, changes in master but not develop. This wont need a release
Check that instructions make sense. 
Anyone but me
=> Sync code and commits between develop and master - Update instructions for running new search

config/config.go
updated dp-design-version hash
=> updated dp-design-version hash

config/config.go
=> updated design system commit hash

data/filter.go, mapper/mapper.go, mapper/mapper_test.go
Remove "topic" content type from filters list
Anyone
=> Release 0.19.0

assets/templates/partials/filter.tmpl, config/config.go
https://trello.com/c/XGHBq4pl/1055-default-content-type-should-be-open
https://trello.com/c/8CJhkUd7/1061-remove-need-an-earlier-release-section-from-search-results-page
Removed some un-needed copy, and updated the design system
=> Various ds bugs

config/config.go
A simple hash change to the latest design system commit.
=> updated design system

assets/templates/partials/standalone-search.tmpl, config/config.go
class name change and design system hash updated
=> class name change and design system hash updated

assets/templates/partials/results.tmpl
removed keywords from search result
https://trello.com/c/y1C4RPuI/1062-remove-keywords-from-search-results
Read the code and/or view locally.
Anyone who knows the repo.
=> removed keywords from search result

go.mod, go.sum
I updated to the latest dp-renderer so that some translations present on there will show on the search page.
https://trello.com/c/6mgQjCnI/1067-footer-translation
Read the code or test locally.
Anyone.
=> update to the latest dp-renderer

mapper/mapper.go
Language toggle will now preserve query params.
https://trello.com/c/7T0EmAsv/1131-toggle-from-en-cy-cy-en
Read through/pull.
Anyone.
=> lang-toggle-with-query

assets/templates/partials/filter.tmpl, config/config.go
Added google tag manager functionality for the filters.
Linked to this work:
https://github.com/ONSdigital/dp-design-system/pull/76
https://trello.com/c/vZZ3QT0l/1120-filter-push-event
Read through or pull.
Anyone with JS knowledge.
=> added data attributes for google tag manager

config/config.go, config/config_test.go
add `ENABLE_CENSUS_TOPIC_FILTER_OPTION` flag
Anyone
=> add ENABLE_CENSUS_TOPIC_FILTER_OPTION flag

config/config.go
=> DS hash update

config/config.go
Update commit hash to design system that includes highlighting for search results. 
See the commit hash in `config.go` matches the commit hash for [release 1.2.0 of the design system](https://github.com/ONSdigital/dp-design-system/commit/17dfae1cef73608f5ab5ed9dee6e6917c5ea71cd). 
Anyone
=> add highlighting for search results

assets/templates/partials/summary.tmpl
only show additional results when no results
Anyone
=> only show additional results when no results

assets/locales/service.cy.toml, assets/locales/service.en.toml, assets/templates/partials/standalone-search.tmpl, assets/templates/partials/summary.tmpl, assets/templates/search.tmpl
- add in new Welsh translations
Anyone
=> add in new Welsh translations

assets/locales/service.cy.toml, assets/locales/service.en.toml, assets/templates/partials/filter.tmpl
Added some translation for the filter items and also the heading "Content type"
Read the code or run locally if you like.
Anyone
=> translation for the filter

assets/locales/service.cy.toml, assets/locales/service.en.toml, assets/templates/partials/filter.tmpl, config/config.go, data/query.go, data/topic-filter.go, handlers/handlers.go, mapper/mapper.go, mapper/mapper_test.go, model/search.go
I have added the topics categories to work the same way as regular categories in anticipation of topics coming from the API.
https://trello.com/c/RX2xaXgE/1090-search-controller-update-controller-data-model-with-topics-filter
https://trello.com/c/upcLpqFt/1095-search-controller-add-checkbox-to-search-results-page
In handlers/handlers.go line 153 change count to 1 to see the changes appear visually
Styling is found in the branch of dp design system
https://github.com/ONSdigital/dp-design-system/tree/topic-filter
Anyone.
=> Topic filter

assets/templates/partials/filter.tmpl, config/config.go
- Add in disabled checkboxes
- Bump dp-design-system version to `1.9.0` / `8f79004`
- Some format changes/fixes
Anyone
=> Add in disabled checkboxes (instead of hiding checkboxes)

config/config.go
Update reference to latest design system release which contains banner and service message styling. 
See that commit hash `f1f6886` matches the [commit hash for the latest release](https://github.com/ONSdigital/dp-design-system/releases) for the dp design system. 
Anyone.
=> update reference to dp design system

mapper/mapper.go, mapper/mapper_test.go
A fix for the census filter currently showing at the top of the search results page when using new search.
Have a gander.
Anyone
=> the topic filter flag can now hide topic filters

config/config.go
Update reference to design library which includes change to make heading font smaller. 
See that commit hash in `congif.go` matches [latest release hash](https://github.com/ONSdigital/dp-design-system/releases/tag/v1.13.0) for `dp-design-library`. 
You!
=> make heading font smaller

Dockerfile.concourse
install an uptodate tzdata package to fix summer time issues in an env
Describe the steps required to test the changes.
=> install an uptodate tzdata package to fix summer time issues

go.mod, go.sum
See title - Imports an update to the search beta banner
Check changes make sense
Anyone
=> Update dependency dp-renderer to latest

go.mod, go.sum
=> Update dp-renderer library to use v1.36.0

data/pagination.go
Add check to see if total pages is less than pages we want to display  to prevent page numbers outside of range
Anyone
=> Release 0.32.0

config/config.go
design system bump
No special instructions.
Anyone.
=> design system bump

config/config.go
Update reference to `dp-design-system`. 
See that tests pass and code makes sense. 
Anyone but me.
=> update library reference

apperrors/errors.go, data/filter.go, data/filter_test.go, data/query.go, data/query_test.go
When user inputs bad data via query parameters return 400 bad request (we will want a 400 template to be rendered in the future).
- All ci checks pass (unit, build, component, lint and audit)
- If the topic or content type filters have incorrect values throw 400 bad request, in all other cases call Search API and render search results, except when the query term has less than 3 characters and no filters are set where we render page with no results (this should display a message on search results page informing user to input more than 3 characters into search bar - waiting on UX).
Anyone
=> Rework validation on user input

go.mod, go.sum, handlers/handlers.go
Publishing subnets require auth.  Switching to the SDK broke the auth, this should hopefully restore it.
Requires https://github.com/ONSdigital/dp-search-api/pull/184 
!me
=> fixed regression where auth no longer works in publishing subnet

assets/templates/partials/results.tmpl, mapper/mapper.go
Correctly check if topic filter exists as a url parameter on search page to determine if a checkbox should be selected or not
- Sanity check code
Anyone
=> Handle topic filter checkboxes correctly

config/config.go
Update design system
See that code makes sense. 
Anyone but me.
=> udpate design hash

assets/templates/partials/filter.tmpl
Fixed markup for collapsible to match design-system as was not opening and closing. 
Boot up frontend-search-controller, dp-design-system
Tunnel to API Router
Make search request
Try to open / close content-type
FE dev.
=> fix content type open close

config/config.go
Update design system with commit has that contains fix for checkboxes. 
See that commit hash is the same as [dp-design-system Release 2.13.0](https://github.com/ONSdigital/dp-design-system/releases/tag/v2.13.0)
!me
=> update hash with fix for checkboxes

config/config.go
Update design system hash
See that code makes sense and tests pass. 
!me
=> add fix for scrolling on mobile

assets/templates/partials/filter.tmpl
Removed census overall count due to risks of incorrect numbers.
Run controller, port forward to sandbox api. 
Observe lack of census count
Not me.
=> remove census count

assets/templates/partials/filter.tmpl
-  add margin so user can select button on iphone
See that tests pass and code makes sense
!me
=> allow user to select button on iphone

assets/templates/partials/filter.tmpl, assets/templates/partials/sort.tmpl
Fixed styling for non-js buttons
Turn off js - check filter / sort buttons. 
Not me.
=> Fix nonjs button styling

config/config.go
Update design hash to add zero results JS/CSS
Check hash matches
Not me.
=> Update design hash for zero results

assets/templates/partials/results.tmpl, assets/templates/search.tmpl, config/config.go
Added Clear all back in at top of filter box - allowed it to work for any URL pattern. 
Load with https://github.com/ONSdigital/dp-design-system/pull/163 and check functionality. 
=> Add clear all to filter box

config/config.go, data/query.go, data/sort.go, mapper/mapper.go, mapper/mapper_test.go
Changed the data to sort by date by default
Enable flag, look at the page, check sort is date, then select a drop down to ensure it changes.
!me
=> dataset: set a default sort to date, removed relevance

assets/templates/partials/search-pagination.tmpl
Fix spacing between count and page buttons. 
Check spacing. 
Not me.
=> Fix pagination spacing

handlers/handlers.go
Add user_requested_data to dataset finder. 
Load search controller, ensure you have an item of static_adhoc in search index with census topic associated. Ensure it appears. 
Not me.
=> Add static ad hoc to dataset finder

config/config.go
Updated design hash for latest design-system changes. 
Check hash ok. 
Notme.
=> Update design hash

README.md
Added missing env vars from readme table
Check all matches
Not me.
=> Tidy env var table

service/service.go
Moved navigation update to outside of publishing conditional.
Activate publishing mode and hit /search - it should now render.
Notme.
=> Fix navigation update for publishing mode

README.md, config/config.go, config/config_test.go, mapper/mapper.go, mapper/mapper_test.go
Removed feature flag for noindexing search pages as no longer required. 
Check all traces been removed and checks passed. 
Not me.
=> Remove no index search feature flag

assets/templates/data-aggregation-page.tmpl, assets/templates/partials/count.tmpl, features/aggregation.feature, features/search.feature, features/steps/component.go, features/steps/fakeapi.go, features/steps/steps.go
Added h1s to data aggregation pages
Added basic skeleton component tests
Check looks ok with data aggregation pages on.
Check tests pass
Not me.
=> Add h1s to data aggregation pages

config/config.go, go.mod, go.sum
Bumped topic api sdk version
Check seems ok (removed a log statement)
Not me.
=> Upgrade topic api sdk

assets/templates/partials/data-filters/topic-filter.tmpl
Fixed topic filter spacing
Check seems ok
Not me.
=> Fix topic filter spacing

README.md, config/config.go, main.go, service/service.go
Implement otel feature flag.
Ensure the tests pass and the changes make sense.
Anyone ONS.
=> Implement otel feature flag

assets/locales/service.cy.toml, assets/locales/service.en.toml, mapper/mapper.go
Update aggregation pages titles - translation files and hardcoded (💩) metadata titles
=> Update aggregation pages titles

assets/templates/data-aggregation-page.tmpl, assets/templates/search.tmpl, assets/templates/time-series-tool.tmpl
add aria-live attributes to search and data agrregation results
Anyone
=> add aria-live attributes to search and data agrregation results

go.mod, go.sum
Upgrade to dp renderer v2.11.0
Not me
=> Update dp-renderer/v2 to version 2.11.0

assets/templates/partials/sort.tmpl
Class being listened to in dp-design system was removed, this has stopped sort working. 
https://github.com/ONSdigital/dp-design-system/blob/bc5cfabfc4a9aa34b96273066d28b5c4d4d7c089/src/js/dp/search.js#L342
Portforward to api router in sandbox, run design-system. Check sort works. 
Frontend dev.
=> Fix sort listeners

features/aggregation.feature, features/steps/component.go, features/steps/steps.go, handlers/handlers.go, handlers/handlers_test.go
add rss for aggregation topics/subtopics
Code conforms to current standards
Unit test pass and have coverage of inserted code
Component tests pass and cover inserted code 
(tag for added tests agg_rss add Tags:                "agg_rss", line 63 of main_test.go)
any one but me
=> add rss for aggregation

cache/mock.go, cache/mock_test.go, cache/private/private_topic.go, cache/public/public_topic.go, cache/topic.go, features/aggregation.feature, handlers/handlers.go, handlers/handlers_test.go
validate topic hierarchy in url path
Check code is ok
Pull branch
set EnableDataAggregationPages to 'true'
set EnableTopicAggregationPages to 'true'
run application and try accessing a route with topic, subtopic and subsubtopic in its url from your browser
ensure that the wrong topic hierarchy in route returns page not found
Ensure correct data is displayed and cache working.
Anyone
=> validate topic hierarchy

Makefile, cache/private/private_topic.go, cache/public/public_topic.go, cache/subtopic.go, ci/scripts/build.sh, ci/scripts/component.sh, ci/scripts/lint.sh, ci/scripts/unit.sh
- use`RLock` when reading cache
- tidy up some logging
ensure functionally same
!me
=> tidy logging; change a Lock() to RLock()

dp-frontend-search-controller.nomad
As per title.
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.
=> Ensure deployments spread over availability zones

cache/private/private_topic.go, cache/private/private_topic_test.go, cache/public/public_topic.go, cache/public/public_topic_test.go, service/service.go
remove go routine in recursion and track recursion depth
Check code is ok.
Anyone, not me
=> remove go routine in recursion and track recursion depth

cache/private/private_topic.go, cache/public/public_topic.go, cache/topic.go, data/query.go, features/steps/steps.go, handlers/handlers.go
=> fix some error message, make others unique

cache/constants.go, cache/mock.go, cache/mock_test.go, cache/private/private_topic.go, cache/private/private_topic_test.go, cache/public/public_topic.go, cache/public/public_topic_test.go, cache/subtopic.go, cache/subtopic_test.go, cache/topic.go, handlers/handlers.go, service/service.go
Cache update fix and refactored data topic cache impl
- Check code is ok
- Pull branch
- set EnableAggregationPages and EnableTopicAggregationPages to 'true'
- run application and try accessing a route with topic, subtopic and subsubtopic in its url from your browser
- Ensure correct data is displayed and cache working.
Not me.
=> topic cache refactor and update fix

mapper/mapper.go, mapper/mapper_test.go
Refactored RSS link generation - makes it simpler, and also I'm suspicious of this function in the mem leak investigation.
Check generates RSS link correctly - switch on agg pages and go to:
/publications
/data
Frontend go dev.
=> Refactor RSS link creation

go.mod, go.sum
Upgrade dp-renderer to resolve OOM kills
To review you need to generate multiple server side validation errors in welsh that use the error summary component.
This can be done by setting your 'lang' cookie to 'cy' and going to /allmethodologies?page=74&filter=qmi
Go dev.
=> Upgrade dp-renderer to resolve oom kills

config/config.go, config/config_test.go
bump design system commit hash
Anyone
=> bump design system commit hash

handlers/handlers_test.go, mapper/mapper_test.go
Describe what you have changed and why.
Describe the steps required to test the changes.
=> remove parallel test when InitialiseLocalisationsHelper used

ci/component.yml, handlers/handlers_test.go, mapper/mapper_test.go
Pin's chrome go and fixes flakey unit tests
Ensure component test passes and unit tests pass
not me.
=> Pin chrome-go

handlers/handlers.go, handlers/handlers_test.go
Add clean up query params func `sanitiseQueryParam`
Anyone
=> Add clean up query params func

features/relateddata.feature, features/steps/component.go, features/steps/fakeapi.go, features/steps/steps.go
Describe what you have changed and why.
Describe the steps required to test the changes.
=> Add related data component test

handlers/handlers.go, handlers/handlers_test.go, handlers/related_data.go
Fixed previousreleases and relateddata in publishing mode. 
Additionally switched over all auth to Authorization header from FlorenceToken header. 
Run Florence, Frontend router and this controller
Port forward API router to sandbox
Login to Florence
Access previous releases or related data via Florence url (localhost:8081) - all works now. 
Frontend dev.
=> Fix bulletin extension in publishing mode

assets/locales/service.cy.toml
Fixes a couple of Welsh translations
- Previous -> Blaenorol
- Previous releases -> Datganiadau blaenorol
Sense check
Not me
=> Update Welsh translations

config/config.go, config/config_test.go
- Update release version for `dp-design-system`
- New version posts to `dp-feedback-api`
Check release hash is the latest [release](https://github.com/ONSdigital/dp-design-system/releases)
!Me
=> Update design system version

handlers/handlers.go
Downgraded invalid topic path to info from error as it is a frequent user behaviour due to how we manage the routing. 
Check looks ok. 
Not me.
=> Downgrade topic path error to info
