mapper/mapper.go, mapper/mapper_test.go
- Change the sort query name from `sortBy` to `sort` to follow `dp-search-query` naming convention
- Check if it looks good
Anyone - Justin made the changes
=> change sort query name

data/pagination.go, data/pagination_test.go, handlers/handlers.go, handlers/handlers_test.go, mapper/mapper.go
Fix pagination showing more than default max results
While running new search you should no longer see pages and result beyond default max result currently set at 500. 
e.g if you have results at 10 per page you should only be able to get 50 pages no more, or if set at 50 per page then only 10 pages
Anyone
=> Fix pagination showing more than default max results

assets/templates/search.tmpl
Extra `main` element was found on one of the new search pages. This is now removed. This has been checked with aXe and Lighthouse which shows there is no longer a duplicate `main` tag. 
On new search, inspect page and see that there is only one `main` element. 
Anyone but me.
=> remove extra main element

assets/templates/partials/filter.tmpl
Checkboxes had non-unique values so they could only select the first checkbox. Added templating to variables so that `id` and `for` values are unique. 
On new search results page on the left under `Content types to show`, see that one can now choose multiple checkboxes. Inspect code and see that `id` and `for` should be the selected content type and not `$id`.  
Anyone but me.
=> add templating to id and for

go.mod, go.sum
Update reference to dp-renderer library to latest version. 
See that url ending is `/feedback` and not does not contain at the end `?service=cmd`. Page still populates under "What's it to do with?". Radio with "This new service (customising data by applying filters)" is no longer an option.  
Anyone but me.
=> update reference to renderer library

go.mod, go.sum
Update to newest release of `dp-renderer`
See that dp-renderer version matches the lastest release (1.9.5) of the [dp-renderer library](https://github.com/ONSdigital/dp-renderer/releases/tag/v1.9.5) 
Anyone but me
=> update to newest release of dp-renderer

assets/templates/partials/pagination.tmpl, assets/templates/search.tmpl, config/config.go
Updated the search template to include a pagination div.  This allows for easier styling for the pagination partial
- requires that https://github.com/ONSdigital/dp-design-system/pull/45 has been merged
- pull the latest dp-design-system
- do a search
- the pagination at the bottom of the results should display horizontally
Anyone
=> fixed search pagination

assets/templates/partials/filter.tmpl, assets/templates/partials/results.tmpl, config/config.go
- Added styling for the search filter
- Added additional logic around the categories to help with how the filters behave
- update the commit ref for the dp-deign-system
- added additional
- ensure you have the latest `dp-design-system`
- pull this branch and run
- do a search
- filter the search on the left
- the filters should appear closed until you have selected a category type
- when the page reloads from the filter, the filter should remain selected and open where appropriate.
- this should also work if you do a filter and then manually refresh the page
Anyone
=> added logic for filter open style

assets/templates/partials/filter.tmpl, assets/templates/partials/results.tmpl, data/filter.go, data/filter_test.go, handlers/handlers.go, mapper/mapper.go, mapper/mapper_test.go, model/search.go
1. Change the field names in `ContentType` struct from `Type` -> `Group` and `SubTypes` -> `Types`. This gives clarity on what each field means. This is an example of how each field links to each other:
```
Publication (Category)
-> Article (Group)
-> -> "articles","static_articles" (Types)
```
2. Moved the logic to get the search result `Type` `LocaliseKey` from the template to the controller 
- Check if the code changes makes sense
- Run locally and see if the search page is functioning as normal
- Check if the tests pass
Anyone
=> update type field and move loop logic to controller

assets/templates/partials/results.tmpl
Markup for the results that link to the product page.
Related to:
https://trello.com/c/uqVhFuKy/957-product-pages-update-search-controller-to-use-new-look-and-feel
Review the code and ideally view locally by pulling this branch and also the other related branch on dp-design-system:
https://github.com/ONSdigital/dp-design-system/pull/54
Anyone.
=> special formatting for product pages

data/filter.go, mapper/mapper.go, mapper/mapper_test.go
Remove topic filter type from web filters
- Run search
- "Topic" filter type under "Other" should no longer appear
- "Other" result count should be correct
Anyone
=> Remove topic filter type from web filters

assets/templates/partials/filter.tmpl, mapper/mapper.go, mapper/mapper_test.go
fix filter item counts appearing as -1
- check count is above 0 before removing 1 from count otherwise skip
- show filter item if greater than one rather than equal to 0, seems a bit more robust and fixes this issue if any other mapper issues
Search for `CF36` and there will be a -1 count for "Other" after pulling these changes "Other" should have zero count and not appear. 
If you don't have content for `CF36` locally you can point your search controller at the prod api e.g. `make debug API_ROUTER_URL="https://api.beta.ons.gov.uk/v1"`
Anyone
=> fix filter item counts appearing as -1

assets/templates/partials/results.tmpl, config/config.go
A loading indicator to show results are taking a while to arrive, there is a data label included as an alternative message in the case of server issues.
> As a website user, with a slow internet connection
> I want to know that my search worked
> so that I am reassured and do not refresh
> 
> 
Required dp-design-system changes: https://github.com/ONSdigital/dp-design-system/pull/85
https://trello.com/c/08BLV9Xr/1058-add-loading-indicator-to-search-results-page?filter=label:Front%20End
Read or pull. Don't forget the dp-design-system counterpart listed above.
Anyone.
=> a loading message on the search page

assets/templates/partials/filter.tmpl, cache/private/census_topic.go, cache/private/census_topic_test.go, cache/public/census_topic.go, cache/public/census_topic_test.go, cache/topic.go, cache/topic_test.go
- Render topic filters with new topic model
- Return an empty census topic object when there is a failure in updating the cache for the census topic. If we pass `nil`, it will error when trying to access that object
- Check if the changes make sense
- Anyone
=> render topic filters with new topic model

apperrors/errors.go, assets/templates/partials/filter.tmpl, cache/mock.go, cache/mock_test.go, cache/private/census_topic.go, cache/private/census_topic_test.go, cache/public/census_topic.go, cache/public/census_topic_test.go, cache/topic.go, cache/topic_test.go, config/config.go, data/query.go, data/topic_filter.go, data/topic_filter_test.go, handlers/handlers.go, handlers/handlers_test.go, mapper/mapper_test.go, service/service.go
- Update dp-design-system hash (https://github.com/ONSdigital/dp-design-system/releases/tag/v1.21.0)
- Update `filter.tmpl` to render and use topic filters in the search page
- Get the first instances of the topics key in the url and its corresponding value
- Set topic ID as key for the cache map for topics filter - the id will not change but the name of the topic can change
- Handle when topic is not found - the search page should still be rendered
- Check topic query with root topic id
- Return empty topic rather than nil to handle caching failures better
- Check if the code changes make sense
- Check if the test passes …
=> update handling of topic filter

cache/mock.go, cache/mock_test.go, data/query.go, data/query_test.go, data/topic_filter.go, data/topic_filter_test.go, handlers/handlers.go
- Separate validation of the topic query and updating the topic query with subtopics
- `reviewTopicFilters` func should only check if the topic id given by the user is valid
- `updateTopicsQueryForSearchAPI` func should update the query with subtopics to be sent to search-api
- Check if the code changes make sense
- Check if the test passes
- Anyone
=> separate validation of the topic query and updating the topic query with subtopics

data/pagination.go
add check to see if total pages is less than pages we want to display to prevent page numbers outside of range
stop:
fix:
- point your local search controller at prod api e.g. `make debug API_ROUTER_URL="https://api.beta.ons.gov.uk/v1"`
- visit http://localhost:20000/search?q=LANGUAGE&filter=bulletin&filter=article&page=3
- view difference before and after code fix
- test other pages for no breakages
Anyone
=> add check to see if total pages is less than pages we want to display to prevent page numbers outside of range

go.mod, go.sum
Bump to latest `dp-renderer` library with fix for screenreader reading feedback confirmation on search pages. 
See that library is bumped to `1.46.0`
Anyone.
=> bump library

assets/templates/partials/filter.tmpl, cache/mock.go, cache/mock_test.go, cache/private/census_topic.go, cache/private/census_topic_test.go, cache/public/census_topic.go, cache/public/census_topic_test.go, cache/subtopic.go, cache/subtopic_test.go, cache/topic.go, data/topic_filter.go, data/topic_filter_test.go, handlers/handlers.go, handlers/handlers_test.go, mapper/mapper.go, model/search.go
- Topic cache updated to include subtopic data, labels and release dates as well as ids
- Search results page updated to display the topic filters (english only as this is what is stored in topics API)
- Sanity check changes
Anyone
=> Update search topic filters to include census subtopics

apperrors/errors.go, handlers/handlers.go
Search is not rendering a search page when there is an invalid query (less than 2 characters). Search should render a blank search page (not a zero results page).
See that code makes sense.
Anyone.
=> render search page when user inputs  invalid query

assets/templates/partials/summary.tmpl
Only show "Results for" when there is a query parameter otherwise "Results" should be displayed
Anyone
=> only show count if there is a query param

.golangci.yml, mapper/mapper.go
See title
Previous split on empty string resulted in 1 item being added to the array used for determining if the "census" checkbox should be checked; this resulted in the census checkbox always being checked even if no topic filters were set. See image below for problem this PR fixes
Sanity check changes
Anyone
=> Fix handling of census checkbox

assets/templates/partials/filter.tmpl, assets/templates/search.tmpl
Adding id's in templates for JS [in this PR](https://github.com/ONSdigital/dp-design-system/pull/156) which fixes a bug for tabbing to checkboxes
See that tests pass and code makes sense 
!me
=> add ids for buttons

assets/templates/partials/filter.tmpl
On some iphone models, the user is unable to select the "Show results" button because it interferes with the .
See that tests pass and code makes sense 
https://user-images.githubusercontent.com/16807393/226338995-768173c3-b2ae-45ad-b3e2-d75241aff683.MP4
!me.
=> allow user to select button on iphone

assets/templates/partials/filter.tmpl
Removed feature that disables options when they have 0 results. 
Open /search with a difficult query ('optimisation') and check the topic or content type filters. 
Not me.
=> Stop inputs disabling on zero count

assets/templates/partials/filter.tmpl, assets/templates/partials/results.tmpl, mapper/mapper.go, model/search.go
Added different rendering if it's on the census dataset finder page and added Population Type to the render. 
Connect search controller to sandbox search api and view the census dataset finder - also ensure normal search is not affected. 
Not me.
=> Add population type to dataset finder rendering

assets/locales/service.cy.toml, assets/locales/service.en.toml, assets/templates/partials/data-aggregation-results.tmpl, assets/templates/time-series-tool.tmpl, features/steps/component.go, features/timeseries.feature, mapper/mapper.go, model/search.go
Added CDID and DatasetID to the timeseries explorer for parity with Babbage. They will appear on any aggregated page if there is a CDID / DatasetID mapped but I think that's ok?
Also hid the type on timeseries explorer (as they're always timeseries)
Also swapped the title for an H1 and removed redundant logic for datasetfinder
Port forward to api router and run and see
Frontend Go Dev.
=> Add CDID and DatasetID to timeseries explorer

features/aggregation.feature, features/timeseries.feature, handlers/handlers.go, handlers/handlers_test.go
Fixed 500 / 400 errors on bad params. Instead map them to the page to allow rendering of errors. Also added tests for data aggregation pages handlers. 
Check looks ok, tests pass. Optionally:
- switch on aggregated data pages
- port forward to sandbox api router
- access /timeseriestool or /alladhocs and try a page limit higher than 50 (51 / 52 in prod throw 400s, 53+ throws 500)
not me.
=> Fix errors on high page count

data/filter.go, data/filter_test.go, handlers/handlers.go
Added a known list of unused content type filters - this will reduce overall logging by the app by around 300K log entries a day. 
Run the app, port forward to api router in aws and check for 'unrecognised filter type returned from api'. Should be none. Check remaining filters still work. 
Not me.
=> Filter unrecognised filter logging for known unused filters

mapper/mapper.go, mapper/mapper_test.go
This stops the aggregation pages using a `noindex` metatag.
_Before_
_After_
Pull this branch
Run dp-frontend-search-controller using make debug ENABLE_REWORKED_DATA_AGGREGATION_PAGES=true
Port forward the api router to sandbox dp ssh sandbox web 1 -p 23200:localhost:10800
Head to these and open the console (F12): 
- http://localhost:25000/datalist
- http://localhost:25000/timeseriestool
Check if any of them have a `noindex` metatag
Ensure `/search` still has one
- http://localhost:25000/search
Anyone
=> Fix/remove SearchNoIndexEnabled

data/filter.go
Added more unused content types:
- compendium_data
- reference_tables
- home_page
- home_page_census
Check ok - can also check these are genuine content types in https://api.beta.ons.gov.uk/v1/search?sort=title&q=
Check they're not mapped anywhere else in this application. 
Not me.
=> Add more unused content types

assets/templates/partials/data-aggregation-results.tmpl
Remove erroneous dateFormat from CDID / Series ID in timeseriestool
Check looks ok, tests pass. 
Optionally:
- port forward to api router
- run with EnableAggregationPages switched to true
- visit /timeseriestool
- see that 'failed to parse time' no longer appears in logs. 
Not me.
=> Remove dateFormat from dataset metadata

go.mod, go.sum
Bumped to 1.13.1 to avoid a cached version of dp-renderer that doesn't have the changes. 
Check looks ok. 
Not me.
=> Bump render version to avoid cached version

handlers/handlers.go
Fix agg pages in publishing mode when logged in to florence.
Check consistency with approach for main search (which works). 
To test:
Populate local search index, run florence in SecAuth mode (`SharedConfig.EnableNewSignIn`) and connect to sandbox api router for auth / search api / zebedee. 
Login to florence (to get auth cookies) and then access aggregated page routes (/alladhocs, /economy/publications). Requires `EnableTopicAggregationPages` and `EnableAggregationPages` to be switched on. 
Not me.
=> Fix aggregated pages in publishing mode

handlers/handlers.go, handlers/handlers_test.go
Fix incorrect counts for filters in subtopic aggregated pages
Check code is ok.
Run and check that the total number of the counts under the content type section equals the total results on the "/economy/datalist" page.
Anyone, not me.
=> fix incorrect filter count  in subtopic aggregated pages

data/query.go, handlers/handlers.go
Set the parent page data type on the API query to fix return compendia and compendia chapters in `/previousreleases` page
Anyone
=> Add parent content type setter func

mapper/mapper.go, mapper/related_data.go
This [fixes](https://jira.ons.gov.uk/browse/DIS-2001) the switch language not working on /relateddata and /previousreleases
You can do `make debug API_ROUTER_URL=https://api.dp.aws.onsdigital.uk/v1`
Then checkout the language switches on these two
- http://localhost:25000/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/uklabourmarket/october2023/relateddata
- http://localhost:25000/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/uklabourmarket/previousreleases
Anyone
=> Fix switch language on relateddata and previousreleases

assets/templates/partials/list.tmpl
✅ [Add missing dataset summary on /relateddata pages](https://jira.ons.gov.uk/browse/DIS-2092)
Sense check
Image review
!me
=> fix/add missing summary for /relateddata pages

assets/templates/partials/list.tmpl
Added Dataset ID if present to results list pages.
I haven't extended tests with these as we currently don't check what they look like anyway. We should do this better in future but I don't think this is the PR to do it in. 
Run service, port forward to sandbox api router and run a related data page with datasets on - see visible dataset IDs and it not appearing if they're not there. 
=> Add datasetID if present

apperrors/errors.go, cache/topic.go, data/filter.go, data/pagination.go, data/query.go, data/string.go, handlers/handlers.go, handlers/related_data.go
Downgraded several client side errors to info logging as stack trace is not useful here as it's expected behaviour. This means the logs are being clogged up. 
Check looks ok, tests pass.
Not me.
=> Downgrade client errors logging to info
